# Generated by Django 6.1 on 2026-08-27 20:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی داوطلب')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, verbose_name='جنسیت')),
                ('exam_group', models.CharField(max_length=100, verbose_name='گروه آزمایشی')),
                ('exam_year', models.PositiveIntegerField(verbose_name='سال کنکور')),
                ('province', models.CharField(max_length=100, verbose_name='استان محل سکونت')),
                ('city', models.CharField(max_length=100, verbose_name='شهر محل سکونت')),
                ('quota', models.CharField(choices=[('region_1', 'منطقه ۱'), ('region_2', 'منطقه ۲'), ('region_3', 'منطقه ۳'), ('martyr_5', 'ایثارگران ۵ درصد'), ('martyr_25', 'ایثارگران ۲۵ درصد'), ('other', 'سایر')], max_length=30, verbose_name='سهمیه')),
                ('region', models.CharField(blank=True, max_length=50, verbose_name='منطقه')),
                ('native_area', models.CharField(blank=True, max_length=150, verbose_name='ناحیه بومی')),
                ('native_pole', models.CharField(blank=True, max_length=150, verbose_name='قطب بومی')),
                ('rank_in_quota', models.PositiveIntegerField(blank=True, null=True, verbose_name='رتبه در سهمیه')),
                ('rank_in_region', models.PositiveIntegerField(blank=True, null=True, verbose_name='رتبه در منطقه')),
                ('national_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='رتبه کشوری')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='تراز کل')),
                ('exam_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='تراز کنکور / آزمون اختصاصی')),
                ('academic_record_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='تراز سوابق تحصیلی')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='تراز نهایی / نمره کل نهایی')),
                ('allowed_daytime', models.CharField(choices=[('allowed', 'مجاز'), ('not_allowed', 'غیرمجاز'), ('unknown', 'نامشخص')], default='unknown', max_length=20, verbose_name='مجاز بودن روزانه')),
                ('allowed_night', models.CharField(choices=[('allowed', 'مجاز'), ('not_allowed', 'غیرمجاز'), ('unknown', 'نامشخص')], default='unknown', max_length=20, verbose_name='مجاز بودن نوبت دوم / شبانه')),
                ('allowed_campus', models.CharField(choices=[('allowed', 'مجاز'), ('not_allowed', 'غیرمجاز'), ('unknown', 'نامشخص')], default='unknown', max_length=20, verbose_name='مجاز بودن پردیس خودگردان')),
                ('allowed_azad', models.CharField(choices=[('allowed', 'مجاز'), ('not_allowed', 'غیرمجاز'), ('unknown', 'نامشخص')], default='unknown', max_length=20, verbose_name='مجاز بودن دانشگاه آزاد')),
                ('allowed_payame_noor', models.CharField(choices=[('allowed', 'مجاز'), ('not_allowed', 'غیرمجاز'), ('unknown', 'نامشخص')], default='unknown', max_length=20, verbose_name='مجاز بودن پیام\u200cنور')),
                ('allowed_non_profit', models.CharField(choices=[('allowed', 'مجاز'), ('not_allowed', 'غیرمجاز'), ('unknown', 'نامشخص')], default='unknown', max_length=20, verbose_name='مجاز بودن غیرانتفاعی')),
                ('allowed_other', models.CharField(choices=[('allowed', 'مجاز'), ('not_allowed', 'غیرمجاز'), ('unknown', 'نامشخص')], default='unknown', max_length=20, verbose_name='مجاز بودن سایر دوره\u200cها')),
                ('only_declared_majors', models.BooleanField(default=False, verbose_name='فقط رشته\u200cهای اعلام\u200cشده بررسی شوند')),
                ('max_annual_tuition', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='حداکثر شهریه قابل پرداخت سالانه (تومان)')),
                ('can_pay_night', models.BooleanField(default=False, verbose_name='توان پرداخت شهریه شبانه')),
                ('can_pay_campus', models.BooleanField(default=False, verbose_name='توان پرداخت شهریه پردیس')),
                ('can_pay_azad', models.BooleanField(default=False, verbose_name='توان پرداخت شهریه دانشگاه آزاد')),
                ('can_pay_payame_noor', models.BooleanField(default=False, verbose_name='توان پرداخت شهریه پیام\u200cنور')),
                ('can_pay_non_profit', models.BooleanField(default=False, verbose_name='توان پرداخت شهریه غیرانتفاعی')),
                ('max_distance_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر فاصله از محل سکونت (کیلومتر)')),
                ('accepted_provinces', models.TextField(blank=True, verbose_name='استان\u200cهای مورد قبول')),
                ('rejected_provinces', models.TextField(blank=True, verbose_name='استان\u200cهای غیرقابل قبول')),
                ('preferred_cities', models.TextField(blank=True, verbose_name='شهرهای مورد علاقه')),
                ('rejected_cities', models.TextField(blank=True, verbose_name='شهرهای غیرقابل قبول')),
                ('geographic_distance_is_important', models.BooleanField(default=True, verbose_name='فاصله جغرافیایی اهمیت دارد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل انتخاب رشته',
                'verbose_name_plural': 'پروفایل\u200cهای انتخاب رشته',
            },
        ),
        migrations.CreateModel(
            name='RejectedMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=150, verbose_name='نام رشته')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_majors', to='exam.studentexamprofile', verbose_name='پروفایل داوطلب')),
            ],
            options={
                'verbose_name': 'رشته غیرقابل قبول',
                'verbose_name_plural': 'رشته\u200cهای غیرقابل قبول',
            },
        ),
        migrations.CreateModel(
            name='InterestedMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=150, verbose_name='نام رشته')),
                ('interest_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='امتیاز علاقه از ۱۰')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_majors', to='exam.studentexamprofile', verbose_name='پروفایل داوطلب')),
            ],
            options={
                'verbose_name': 'رشته مورد علاقه',
                'verbose_name_plural': 'رشته\u200cهای مورد علاقه',
                'ordering': ['-interest_score', 'major_name'],
            },
        ),
        migrations.CreateModel(
            name='CriterionWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_reputation', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='اعتبار کلی دانشگاه')),
                ('faculty_quality', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='کیفیت تخصصی دانشکده / گروه آموزشی')),
                ('job_market', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='بازار کار')),
                ('income_potential', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='پتانسیل درآمد')),
                ('immigration_potential', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='امکان مهاجرت')),
                ('academic_career', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='امکان هیئت علمی')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_weights', to='exam.studentexamprofile', verbose_name='پروفایل داوطلب')),
            ],
            options={
                'verbose_name': 'وزن معیار انتخاب رشته',
                'verbose_name_plural': 'وزن معیارهای انتخاب رشته',
            },
        ),
        migrations.CreateModel(
            name='AcceptedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('daytime', 'روزانه'), ('night', 'نوبت دوم / شبانه'), ('campus', 'پردیس خودگردان'), ('azad', 'دانشگاه آزاد'), ('payame_noor', 'پیام\u200cنور'), ('non_profit', 'غیرانتفاعی'), ('other', 'سایر')], max_length=30, verbose_name='دوره مورد قبول')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_courses', to='exam.studentexamprofile', verbose_name='پروفایل داوطلب')),
            ],
            options={
                'verbose_name': 'دوره مورد قبول',
                'verbose_name_plural': 'دوره\u200cهای مورد قبول',
                'constraints': [models.UniqueConstraint(fields=('profile', 'course'), name='unique_accepted_course_per_profile')],
            },
        ),
    ]
