# Generated by Django 6.1 on 2026-09-06 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterionweight',
            name='interest',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='وزن علاقه به رشته'),
        ),
        migrations.AddField(
            model_name='studentexamprofile',
            name='selection_type',
            field=models.CharField(blank=True, choices=[('national', 'کشوری'), ('pole', 'قطبی'), ('area', 'ناحیه\u200cای'), ('province', 'استانی')], max_length=20, verbose_name='نوع گزینش رشته'),
        ),
        migrations.AlterField(
            model_name='criterionweight',
            name='academic_career',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='امکان هیئت علمی'),
        ),
        migrations.AlterField(
            model_name='criterionweight',
            name='faculty_quality',
            field=models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='کیفیت تخصصی دانشکده / گروه آموزشی'),
        ),
        migrations.AlterField(
            model_name='criterionweight',
            name='immigration_potential',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='امکان مهاجرت'),
        ),
        migrations.AlterField(
            model_name='criterionweight',
            name='job_market',
            field=models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='بازار کار'),
        ),
        migrations.AlterField(
            model_name='studentexamprofile',
            name='allowed_azad',
            field=models.CharField(blank=True, choices=[('allowed', 'مجاز'), ('not_allowed', 'غیرمجاز'), ('unknown', 'نامشخص')], default='unknown', max_length=20, verbose_name='مجاز بودن دانشگاه آزاد'),
        ),
        migrations.AlterField(
            model_name='studentexamprofile',
            name='allowed_campus',
            field=models.CharField(blank=True, choices=[('allowed', 'مجاز'), ('not_allowed', 'غیرمجاز'), ('unknown', 'نامشخص')], default='unknown', max_length=20, verbose_name='مجاز بودن پردیس خودگردان'),
        ),
        migrations.AlterField(
            model_name='studentexamprofile',
            name='allowed_daytime',
            field=models.CharField(blank=True, choices=[('allowed', 'مجاز'), ('not_allowed', 'غیرمجاز'), ('unknown', 'نامشخص')], default='unknown', max_length=20, verbose_name='مجاز بودن روزانه'),
        ),
        migrations.AlterField(
            model_name='studentexamprofile',
            name='allowed_night',
            field=models.CharField(blank=True, choices=[('allowed', 'مجاز'), ('not_allowed', 'غیرمجاز'), ('unknown', 'نامشخص')], default='unknown', max_length=20, verbose_name='مجاز بودن نوبت دوم / شبانه'),
        ),
        migrations.AlterField(
            model_name='studentexamprofile',
            name='allowed_non_profit',
            field=models.CharField(blank=True, choices=[('allowed', 'مجاز'), ('not_allowed', 'غیرمجاز'), ('unknown', 'نامشخص')], default='unknown', max_length=20, verbose_name='مجاز بودن غیرانتفاعی'),
        ),
        migrations.AlterField(
            model_name='studentexamprofile',
            name='allowed_other',
            field=models.CharField(blank=True, choices=[('allowed', 'مجاز'), ('not_allowed', 'غیرمجاز'), ('unknown', 'نامشخص')], default='unknown', max_length=20, verbose_name='مجاز بودن سایر دوره\u200cها'),
        ),
        migrations.AlterField(
            model_name='studentexamprofile',
            name='allowed_payame_noor',
            field=models.CharField(blank=True, choices=[('allowed', 'مجاز'), ('not_allowed', 'غیرمجاز'), ('unknown', 'نامشخص')], default='unknown', max_length=20, verbose_name='مجاز بودن پیام\u200cنور'),
        ),
        migrations.AlterField(
            model_name='studentexamprofile',
            name='exam_group',
            field=models.CharField(choices=[('math', 'ریاضی و فنی'), ('experimental', 'علوم تجربی'), ('humanities', 'علوم انسانی'), ('art', 'هنر'), ('languages', 'زبان\u200cهای خارجی')], max_length=20, verbose_name='گروه آزمایشی'),
        ),
    ]
