# Generated by Django 6.1 on 2026-09-06 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در حال پردازش'), ('done', 'تکمیل\u200cشده'), ('failed', 'خطا')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('prompt_used', models.TextField(blank=True, verbose_name='پرامپت ارسال\u200cشده')),
                ('raw_response', models.TextField(blank=True, verbose_name='پاسخ خام هوش مصنوعی')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا (در صورت وجود)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_analysis', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تحلیل تولیدشده',
                'verbose_name_plural': 'تحلیل\u200cهای تولیدشده',
            },
        ),
    ]
